# Generated by Django 4.1.2 on 2023-04-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_messages', to='chat.dialog')),
                ('this_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_message', to='chat.dialog')),
            ],
        ),

        migrations.RemoveField(
            model_name='dialog',
            name='forward',
        ),
        migrations.AddField(
            model_name='dialog',
            name='forward',
            field=models.ManyToManyField(blank=True, null=True, through='chat.Forward', to='chat.dialog')),
    ]
